AppBundle\Entity\Encounter:
    type: entity
    table: Encounter
    gedmo:
        translation:
            locale: locale
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: encounter
    manyToMany:
        scenarios:
            targetEntity: Scenario
            orderBy: {'id':'ASC'}
            mappedBy: encounters
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
    uniqueConstraints:
        encounter_code_idx:
            columns: [ code ]
            
